// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.21.0";

// src/lib/mcp/tools/list_cars.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z } from "npm:zod@^3.23.8";
var list_cars_default = defineTool({
  name: "list_cars",
  title: "List supercars",
  description: "List Owneo's active supercar catalog with brand, model, year, city, participation price and remaining participations.",
  inputSchema: {
    city_slug: z.string().optional().describe("Optional city slug filter (e.g. madrid, barcelona)."),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city_slug, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let query = supabase.from("cars_public").select("id, slug, name, brand, model, year, price, category, status, max_participations, locations(name, slug)").eq("status", "active").limit(limit ?? 20);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).filter(
      (r) => city_slug ? r.locations?.slug === city_slug : true
    );
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { cars: rows }
    };
  }
});

// src/lib/mcp/tools/get_car.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z as z2 } from "npm:zod@^3.23.8";
var get_car_default = defineTool2({
  name: "get_car",
  title: "Get supercar details",
  description: "Fetch full public details of one Owneo supercar by its slug.",
  inputSchema: {
    slug: z2.string().min(1).describe("Car slug, e.g. ferrari-roma-madrid.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("cars_public").select("*, locations(name, slug)").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Car not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { car: data }
    };
  }
});

// src/lib/mcp/tools/list_locations.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.21.0";
var list_locations_default = defineTool3({
  name: "list_locations",
  title: "List Owneo cities",
  description: "List the Spanish cities where Owneo operates.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("locations").select("id, name, slug, country").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { locations: data }
    };
  }
});

// src/lib/mcp/tools/list_my_participations.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.21.0";
function supabaseForUser(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_participations_default = defineTool4({
  name: "list_my_participations",
  title: "List my participations",
  description: "List the validated Owneo participations owned by the signed-in user (car, credits remaining, credits used).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("validated_participations").select(
      "id, participation_number, credits_remaining, credits_per_year, credits_used_this_year, standard_credits_remaining, premium_credits_remaining, credits_reset_date, cars(slug, brand, model, year)"
    ).eq("user_id", ctx.getUserId());
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { participations: data }
    };
  }
});

// src/lib/mcp/tools/list_my_reservations.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z as z3 } from "npm:zod@^3.23.8";
function supabaseForUser2(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_reservations_default = defineTool5({
  name: "list_my_reservations",
  title: "List my reservations",
  description: "List the signed-in user's Owneo reservations (dates, car, status, credits used). Optionally filter by status.",
  inputSchema: {
    status: z3.enum(["pending", "confirmed", "cancelled", "completed"]).optional().describe("Optional reservation status filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = supabaseForUser2(ctx).from("reservations").select(
      "id, start_date, end_date, status, reservation_type, credits_used, standard_credits_used, premium_credits_used, cars(slug, brand, model)"
    ).eq("user_id", ctx.getUserId()).order("start_date", { ascending: false });
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { reservations: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "deafxtmgcqovwqlvktte";
var mcp_default = defineMcp({
  name: "owneo-mcp",
  title: "Owneo",
  version: "0.1.0",
  instructions: "Owneo is a luxury supercar co-sharing platform in Spain (10% participations, 4 weeks/year per share). Use `list_cars`, `get_car`, and `list_locations` for the public catalog. Use `list_my_participations` and `list_my_reservations` to read the signed-in user's own data (RLS-scoped).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_cars_default,
    get_car_default,
    list_locations_default,
    list_my_participations_default,
    list_my_reservations_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.21.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
